spring:
  application:
    name: nintendo-gameInvService
  datasource:
    url: jdbc:postgresql://localhost:5432/u2r94970203
    username: postgres
    password: password

server:
  port: 8085
  servlet:
    contextPath: /videogames